config/routes.rb
Rails.application.routes.draw do
mount Attachinary::Engine => "/attachinary"

  root to: 'boards#index'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :boards do
    resources :reservations, only: [:new, :create, :show, :update, :destroy]
  end

  get "/dashboard", to: "pages#dashboard", as: :dashboard
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :reservations
  has_attachments :photos, maximum: 2

  validates :name, presence: true

  # validates :category, presence: true

  validates :size, presence: true, :numericality => { :greater_than => 4, :less_than_or_equal_to => 9 }

  validates :price_per_day, presence: true

  # validates :description, presence: true

  validates :address, presence: true

  # validates :city, presence: true

  # validates :country, presence: true

  # validates :automatic_reservation

  validates :user, presence: true

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :boards
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :surfer, class_name: "User", foreign_key: "user_id"
  belongs_to :board
  has_one :owner, through: :board, class_name: "User", foreign_key: "user_id", source: "user"


  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  devise :omniauthable, omniauth_providers: [:facebook]

  has_many :reservations
  has_many :boards, dependent: :destroy
  validates :first_name, presence: true
  validates :last_name, presence: true

  def self.find_for_facebook_oauth(auth)
    user_params = auth.to_h.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)

    user = User.where(provider: auth.provider, uid: auth.uid).first
    user ||= User.where(email: auth.info.email).first # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?


protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :surname, :phone_number, :email])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :find_board, only: [:show, :edit, :update]

  before_action :authenticate_user!, only: [:create, :new, :create]

  def index
    if address = params[:address]
      @boards = Board.near(address, 20)
    else
      @boards = Board.all
    end
  end

  def show
  end

  def new
    @board = Board.new
  end

  def create
    @board = current_user.boards.new(board_params)
    if @board.save
      redirect_to dashboard_path(), notice: "Your new board has been created !"
    else
      render :new
    end
  end

  def edit
  end

  def update
    @board.update(board_params)

    redirect_to user_path(@current_user), notice: "Your board has been updated !"

  end

  private

  def board_params
    params.require(:board).permit(:name, :size, :price_per_day, :description, :address, :city, :country, :automatic_reservation, :category_id, photos: [])
  end

  def find_board
    @board = Board.find(params[:id])
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def myboards
    @myboards = board.user
    puts @myboards
  end

  def destroy
    @board = Board.find(params[:id])
    @board.destroy
  end
  def myreservation
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, only: [:dashboard]
  def home
  end

  def dashboard
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

   before_action :find_reservation, only: [:show, :update]
   before_action :find_board, only: [:show, :new, :create]
   before_action :authenticate_user!


  def show
      @reservation = current_user.reservations
  end

  def new
    @reservation = Reservation.new
  end

  def create
    @reservation = Reservation.new(reservation_params)
    @reservation.board = @board
    @reservation.surfer = current_user
    if @reservation.save
      render :show
      # redirect_to board_reservation_path(current_user), notice: "Your reservation is now pending !"
      else
        render :new
      end
  end

  def update
    @reservation.update(reservation_params)
  end

  def destroy
  end

private

  def find_reservation
    @reservation = Reservation.find(:id)
  end

  def reservation_params
    params.require(:reservation).permit(:start_date, :end_date)
  end

  def find_board
    @board = Board.find(params[:board_id])
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
     @user = User.find(params[:id])
  end

  def edit

  end

  def update
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/boards/_form.html.erb
<div class="container">
    <div class="row">
      <div class="col-sm-4 col-sm-offset-4">
        <h1>Post a New Board</h1>
        <%= simple_form_for board do |f| %>
         <%= f.error_notification %>
         <%= f.input :name  %>
         <%= f.association :category %>
         <%= f.input :size, collection: 5..9  %>
         <%= f.input :price_per_day %>
         <%= f.input :description %>
         <%= f.input :address %>
         <%= f.input :automatic_reservation %>

         <%= f.input :photos, as: :attachinary %>


         <%= f.button :submit %>
        <% end %>
      </div>
    </div>
</div>

app/views/boards/create.html.erb
<h1>Boards#create</h1>
<p>Find me in app/views/boards/create.html.erb</p>

app/views/boards/destroy.html.erb
<h1>Boards#destroy</h1>
<p>Find me in app/views/boards/destroy.html.erb</p>

app/views/boards/edit.html.erb
<h1>Boards#edit</h1>
<p>Find me in app/views/boards/edit.html.erb</p>

app/views/boards/index.html.erb
<div class="banner" style="background-image: url('http://image3.redbull.com/rbcom/010/2015-04-29/1331720022267_2/0010/1/1500/1000/2/justine-dupont-surf-big-wave-action-image.jpg');">
  <div class="banner-content">
    <h1>Boards everywhere, free as a bird</h1>
  </div>
  <div class="banner-search_bar">
    <%= simple_form_for :search, url: boards_path, method: :get, html: { class: "form-inline" } do |f| %>
      <%= f.input :address, label: false, placeholder: "Enter a city" %>
      <%= f.button :submit, "Search" %>
    <% end %>
  </div>
</div>

<div class="container">
  <div class="row">
    <% @boards.each do |board| %>
      <%= link_to board_path(board) do %>
        <div class="col-xs-12 col-sm-4">
          <div class="card card-link" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('logo.png');">
            <div class="card-description">
              <%= board.name %>
              <%= board.address %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/boards/new.html.erb
<%= render "form", board: @board %>

app/views/boards/show.html.erb
<div class="container">
    <div class="row">
      <div class="col-sm-4 col-sm-offset-4">
        <h2><%= @board.name %></h2>
        <p><%= @board.address %></p>
        <p><%= @board.price_per_day %>€/day</p>
        <p><%= @board.automatic_reservation %></p>
          <% @board.photos.each do |photo| %>
          <%= cl_image_tag photo.path, width: 200, height: 300, crop: :fill %>
          <% end %>
          <p></p>
          <p></p>
          <%= link_to "Rent the board", new_board_reservation_path(@board), {class: "btn btn-primary"} %>
      </div>
    </div>
</div>

app/views/boards/update.html.erb
<h1>Boards#update</h1>
<p>Find me in app/views/boards/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= cloudinary_js_config %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<% current_user.boards.each do |board| %>
  <h2>Name >>> <%=board.name%></h2>
  <h2>Size >>><%=board.size%></h2>
  <h2>Price per day >>><%=board.price_per_day%></h2>
  <h2>Description >>><%=board.description%></h2>
  <h2>Address >>><%=board.address%></h2>
  <h2>Automatic Reservation >>><%=board.automatic_reservation%></h2>
  <h2>Photos >>><%board.photos.each do |photo|%></h2>
    <%= cl_image_tag photo.path, width: 200, height: 300, crop: :fill %>
    <% end %>
<% end %>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/reservations/create.html.erb
<h1>Reservations#create</h1>
<p>Find me in app/views/reservations/create.html.erb</p>

app/views/reservations/destroy.html.erb
<h1>Reservations#destroy</h1>
<p>Find me in app/views/reservations/destroy.html.erb</p>

app/views/reservations/new.html.erb
<div class="container">
    <div class="row">
      <div class="col-sm-4 col-sm-offset-4">
        <h1>Book this board :</h1>
        <h2><%= @board.name %></h2>
        <p><%= @board.address %></p>
        <p><%= @board.price_per_day %>€/day</p>
        <p><%= @board.automatic_reservation %></p>

      <%= simple_form_for([@board, @reservation]) do |f| %>
        <%= f.input :start_date %>
        <%= f.input :end_date %>
        <%= f.button :submit %>
      <% end %>
      </div>
   </div>
</div>

app/views/reservations/show.html.erb
<div class="alert alert-success">You reservation is now pending !</div>

<h1 class="text-center">Here are my reservations</h1>

<div class="container text-center">
<% current_user.reservations.each do |reservation| %>
<%= reservation.start_date %>
<%= reservation.end_date %>
<%= reservation.board.name %>
<p> <%= reservation.board.price_per_day %> € </p>
<hr>
<% end %>
</div>

app/views/reservations/update.html.erb
<h1>Reservations#update</h1>
<p>Find me in app/views/reservations/update.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
 <div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
    <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form>

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Notification -->
      <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
        <div class="badge-container">
          <i class="fa fa-envelope-o"></i>
          <div class="badge badge-blue">3</div>
        </div>
      <% end %>


      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <% if current_user.facebook_picture_url %>
            <%= image_tag current_user.facebook_picture_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <% else %>
            <%= image_tag "http://www.pieglobal.com/wp-content/uploads/2015/10/placeholder-user.png", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <% end %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "dashboard" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

    <!-- Button (call-to-action) -->

    <%= link_to t(".top_call_to_action", default: "Post New Board"), new_board_path, class: "navbar-wagon-item navbar-wagon-button btn" %>

  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>


<%= @user.email %>
<%= @board = Board.all %>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>